services:
  - type: web
    name: youtube-sponsorship-detector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHONHASHSEED
        value: random
    plan: free
    autoDeploy: true
